# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
