# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-24 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAPI', '0002_auto_20180523_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ShopAPI.Products'),
        ),
    ]
