# Generated by Django 2.0.5 on 2018-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock_number',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
