# Generated by Django 2.0.5 on 2018-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAPI', '0002_auto_20180519_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
