# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAPI', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopAPI.Products'),
        ),
    ]
